(define (problem recovery-problem)
  (:domain recovery-blocks)
  (:objects
    A B C D - block
  )
  (:init
    (HandEmpty)
    (On B A)
    (On C B)
    (On D C)
    (OnTable A)
    (OnTable TABLE)
    (Clear D)
    (Clear TABLE)
    (TargetOn B A)
    (TargetOn C B)
    (TargetOn D C)
  )
  (:goal (and
    (AtTarget B)
    (AtTarget C)
    (AtTarget D)
    (On B A)
    (On C B)
    (On D C)
    (OnTable A)
    (OnTable TABLE)
    (HandEmpty)
  ))
)